const express = require('express');
const db = require('../database/connection');
const router = express.Router();

router.put('/update/part1', (req, res) => {
    const {
        patient_code, 
        first_name,
        last_name,
        age,
        city_of_residence,
        date_of_diagnosis,
        date_of_surgery,
        histopath_result,
        gleason_score,
        date_of_treatment,
        treatment_type,
        ecog_score,
        ht,
        wt,
        bmi,
        bp,
        hr,
        pain_score,
        local_symptoms,
        systemic_symptoms,
        psa,
        creatinine,
        wbc,
        rbc,
        hemoglobin,
        hematocrit,
        platelet_count,
        lactate_dehydrogenase,
        alkaline_phosphatase,
        sgpt_sgot_bilirubins,
        normal_salivary_gland,
        right_obstruction,
        left_obstruction,
        renal_scintigraphy,
        bone_scan,
        metastasis_location,
        lesion_ga_psma,
        lesion_prostate_a,
        lesion_prostate_a_location,
        lesion_prostate_a_suv,
        lesion_prostate_a_measurement,
        lesion_lymph_a,
        lesion_lymph_a_location,
        lesion_lymph_a_suv,
        lesion_lymph_a_measurement,
        lesion_bone_a,
        lesion_bone_a_location,
        lesion_bone_a_suv,
        lesion_bone_a_measurement,
        lesion_brain_a,
        lesion_brain_a_location,
        lesion_brain_a_suv,
        lesion_brain_a_measurement,
        lesion_lungs_a,
        lesion_lungs_a_location,
        lesion_lungs_a_suv,
        lesion_lungs_a_measurement,
        lesion_liver_a,
        lesion_liver_a_location,
        lesion_liver_a_suv,
        lesion_liver_a_measurement,
        lesion_others_a,
        lesion_others_a_location,
        lesion_others_a_suv,
        lesion_others_a_measurement,
        lesion_fdg_ctr,
        lesion_prostate_b,
        lesion_prostate_b_location,
        lesion_prostate_b_suv,
        lesion_prostate_b_measurement,
        lesion_lymph_b,
        lesion_lymph_b_location,
        lesion_lymph_b_suv,
        lesion_lymph_b_measurement,
        lesion_bone_b,
        lesion_bone_b_location,
        lesion_bone_b_suv,
        lesion_bone_b_measurement,
        lesion_brain_b,
        lesion_brain_b_location,
        lesion_brain_b_suv,
        lesion_brain_b_measurement,
        lesion_lungs_b,
        lesion_lungs_b_location,
        lesion_lungs_b_suv,
        lesion_lungs_b_measurement,
        lesion_liver_b,
        lesion_liver_b_location,
        lesion_liver_b_suv,
        lesion_liver_b_measurement,
        lesion_others_b,
        lesion_others_b_location,
        lesion_others_b_suv,
        lesion_others_b_measurement,
        assessment,
        plan } = req.body;
        db('part1')
        .where({patient_code: patient_code})
        .update({
            first_name: first_name,
            last_name: last_name,
            age: age,
            city_of_residence: city_of_residence,
            date_of_diagnosis: date_of_diagnosis,
            date_of_surgery: date_of_surgery,
            histopath_result: histopath_result,
            gleason_score: gleason_score,
            date_of_treatment: date_of_treatment,
            treatment_type: treatment_type,
            ecog_score: ecog_score,
            ht: ht,
            wt: wt,
            bmi: bmi,
            bp: bp,
            hr: hr,
            pain_score: pain_score,
            local_symptoms: local_symptoms,
            systemic_symptoms: systemic_symptoms,
            psa: psa,
            creatinine: creatinine,
            wbc: wbc,
            rbc: rbc,
            hemoglobin: hemoglobin,
            hematocrit: hematocrit,
            platelet_count: platelet_count,
            lactate_dehydrogenase: lactate_dehydrogenase,
            alkaline_phosphatase: alkaline_phosphatase,
            sgpt_sgot_bilirubins: sgpt_sgot_bilirubins,
            normal_salivary_gland: normal_salivary_gland,
            right_obstruction: right_obstruction,
            left_obstruction: left_obstruction,
            renal_scintigraphy: renal_scintigraphy,
            bone_scan: bone_scan,
            metastasis_location: metastasis_location,
            lesion_ga_psma: lesion_ga_psma,
            lesion_prostate_a: lesion_prostate_a,
            lesion_prostate_a_location: lesion_prostate_a_location,
            lesion_prostate_a_suv: lesion_prostate_a_suv,
            lesion_prostate_a_measurement: lesion_prostate_a_measurement,
            lesion_lymph_a: lesion_lymph_a,
            lesion_lymph_a_location: lesion_lymph_a_location,
            lesion_lymph_a_suv: lesion_lymph_a_suv,
            lesion_lymph_a_measurement: lesion_lymph_a_measurement,
            lesion_bone_a: lesion_bone_a,
            lesion_bone_a_location: lesion_bone_a_location,
            lesion_bone_a_suv: lesion_bone_a_suv,
            lesion_bone_a_measurement: lesion_bone_a_measurement,
            lesion_brain_a: lesion_brain_a,
            lesion_brain_a_location: lesion_brain_a_location,
            lesion_brain_a_suv: lesion_brain_a_suv,
            lesion_brain_a_measurement: lesion_brain_a_measurement,
            lesion_lungs_a: lesion_lungs_a,
            lesion_lungs_a_location: lesion_lungs_a_location,
            lesion_lungs_a_suv: lesion_lungs_a_suv,
            lesion_lungs_a_measurement: lesion_lungs_a_measurement,
            lesion_liver_a: lesion_liver_a,
            lesion_liver_a_location: lesion_liver_a_location,
            lesion_liver_a_suv: lesion_liver_a_suv,
            lesion_liver_a_measurement: lesion_liver_a_measurement,
            lesion_others_a: lesion_others_a,
            lesion_others_a_location: lesion_others_a_location,
            lesion_others_a_suv: lesion_others_a_suv,
            lesion_others_a_measurement: lesion_others_a_measurement,
            lesion_fdg_ct: lesion_fdg_ctr,
            lesion_prostate_b: lesion_prostate_b,
            lesion_prostate_b_location: lesion_prostate_b_location,
            lesion_prostate_b_suv: lesion_prostate_b_suv,
            lesion_prostate_b_measurement: lesion_prostate_b_measurement,
            lesion_lymph_b: lesion_lymph_b,
            lesion_lymph_b_location: lesion_lymph_b_location,
            lesion_lymph_b_suv: lesion_lymph_b_suv,
            lesion_lymph_b_measurement: lesion_lymph_b_measurement,
            lesion_bone_b: lesion_bone_b,
            lesion_bone_b_location: lesion_bone_b_location,
            lesion_bone_b_suv: lesion_bone_b_suv,
            lesion_bone_b_measurement: lesion_bone_b_measurement,
            lesion_brain_b: lesion_brain_b,
            lesion_brain_b_location: lesion_brain_b_location,
            lesion_brain_b_suv: lesion_brain_b_suv,
            lesion_brain_b_measurement: lesion_brain_b_measurement,
            lesion_lungs_b: lesion_lungs_b,
            lesion_lungs_b_location: lesion_lungs_b_location,
            lesion_lungs_b_suv: lesion_lungs_b_suv,
            lesion_lungs_b_measurement: lesion_lungs_b_measurement,
            lesion_liver_b: lesion_liver_b,
            lesion_liver_b_location: lesion_liver_b_location,
            lesion_liver_b_suv: lesion_liver_b_suv,
            lesion_liver_b_measurement: lesion_liver_b_measurement,
            lesion_others_b: lesion_others_b,
            lesion_others_b_location: lesion_others_b_location,
            lesion_others_b_suv: lesion_others_b_suv,
            lesion_others_b_measurement: lesion_others_b_measurement,
            assessment: assessment,
            plan: plan
        })
        .then(() => {
            res.json([{event :'success'}])
           
        })
        .catch((err) => {
            res.json([{event: 'error'}])
        })

})

router.put('/update/part2', (req, res) => {
    const { therapy_id, date_radioligand, meds, pre_meds, p2_bp, p2_hr,
        p2_rr, oxygen_sat, date_therapy, radiopharm, activity,
        have_fatigue, have_nausea_vomitting, have_dry_lipmouth,
        have_headache, have_bone_pain, other_side_effect } = req.body;
    db('part2')
    .where({therapy_id: therapy_id})
    .update({
        date_radioligand: date_radioligand,
        meds: meds,
        pre_meds: pre_meds,
        p2_bp: p2_bp,
        p2_hr: p2_hr,
        p2_rr: p2_rr,
        oxygen_sat: oxygen_sat,
        date_therapy: date_therapy,
        radiopharm: radiopharm,
        activity: activity,
        have_fatigue: have_fatigue,
        have_nausea_vomitting: have_nausea_vomitting,
        have_dry_lipmouth: have_dry_lipmouth,
        have_headache: have_headache,
        have_bone_pain: have_bone_pain,
        other_side_effect: other_side_effect
    })
    .then(() => {
        res.json([{event :'success'}])
       
    })
    .catch((err) => {
        res.json([{event: 'error'}])
    })
})

router.put('/update/part3', (req, res) => {
    const { post_therapy_id, date_post_therapy, pts_hour,
        with_spect, lesion_prostate, lesion_lymph,
        lesion_lungs, lesion_bones, lesion_liver,
        dosimetry_saliva, dosimetry_kidney_left,
        dosimetry_kidney_right } = req.body
    db('part3')
    .where({post_therapy_id: post_therapy_id})
    .update({
        date_post_therapy: date_post_therapy,
        pts_hour: pts_hour,
        with_spect: with_spect,
        lesion_prostate: lesion_prostate,
        lesion_lymph: lesion_lymph,
        lesion_bones: lesion_bones,
        lesion_lungs: lesion_lungs,
        lesion_liver: lesion_liver,
        dosimetry_saliva: dosimetry_saliva,
        dosimetry_kidney_left: dosimetry_kidney_left,
        dosimetry_kidney_right: dosimetry_kidney_right
    })
    .then(() => {
        res.json([{event :'success'}])
       
    })
    .catch((err) => {
        res.json([{event: 'error'}])
    })
})

router.put('/update/part4', (req, res) => {
    const {
        follow_up_id,
        follow_up_date, 
        psa,
        creatinine,
        wbc,
        rbc,
        hemoglobin,
        hematocrit,
        platelet_count,
        lactate_dehydrogenase,
        alkaline_phosphatase,
        sgpt_sgot_bilirubins,
        normal_salivary_gland,
        right_obstruction,
        left_obstruction,
        renal_scintigraphy,
        bone_scan,
        metastasis_location,
        lesion_ga_psma,
        lesion_prostate_a,
        lesion_prostate_a_location,
        lesion_prostate_a_suv,
        lesion_prostate_a_measurement,
        lesion_lymph_a,
        lesion_lymph_a_location,
        lesion_lymph_a_suv,
        lesion_lymph_a_measurement,
        lesion_bone_a,
        lesion_bone_a_location,
        lesion_bone_a_suv,
        lesion_bone_a_measurement,
        lesion_brain_a,
        lesion_brain_a_location,
        lesion_brain_a_suv,
        lesion_brain_a_measurement,
        lesion_lungs_a,
        lesion_lungs_a_location,
        lesion_lungs_a_suv,
        lesion_lungs_a_measurement,
        lesion_liver_a,
        lesion_liver_a_location,
        lesion_liver_a_suv,
        lesion_liver_a_measurement,
        lesion_others_a,
        lesion_others_a_location,
        lesion_others_a_suv,
        lesion_others_a_measurement,
        lesion_fdg_ctr,
        lesion_prostate_b,
        lesion_prostate_b_location,
        lesion_prostate_b_suv,
        lesion_prostate_b_measurement,
        lesion_lymph_b,
        lesion_lymph_b_location,
        lesion_lymph_b_suv,
        lesion_lymph_b_measurement,
        lesion_bone_b,
        lesion_bone_b_location,
        lesion_bone_b_suv,
        lesion_bone_b_measurement,
        lesion_brain_b,
        lesion_brain_b_location,
        lesion_brain_b_suv,
        lesion_brain_b_measurement,
        lesion_lungs_b,
        lesion_lungs_b_location,
        lesion_lungs_b_suv,
        lesion_lungs_b_measurement,
        lesion_liver_b,
        lesion_liver_b_location,
        lesion_liver_b_suv,
        lesion_liver_b_measurement,
        lesion_others_b,
        lesion_others_b_location,
        lesion_others_b_suv,
        lesion_others_b_measurement,
        assessment,
        plan } = req.body;
        db('part4')
        .where({follow_up_id: follow_up_id})
        .update({
            follow_up_date: follow_up_date,
            psa: psa,
            creatinine: creatinine,
            wbc: wbc,
            rbc: rbc,
            hemoglobin: hemoglobin,
            hematocrit: hematocrit,
            platelet_count: platelet_count,
            lactate_dehydrogenase: lactate_dehydrogenase,
            alkaline_phosphatase: alkaline_phosphatase,
            sgpt_sgot_bilirubins: sgpt_sgot_bilirubins,
            normal_salivary_gland: normal_salivary_gland,
            right_obstruction: right_obstruction,
            left_obstruction: left_obstruction,
            renal_scintigraphy: renal_scintigraphy,
            bone_scan: bone_scan,
            metastasis_location: metastasis_location,
            lesion_ga_psma: lesion_ga_psma,
            lesion_prostate_a: lesion_prostate_a,
            lesion_prostate_a_location: lesion_prostate_a_location,
            lesion_prostate_a_suv: lesion_prostate_a_suv,
            lesion_prostate_a_measurement: lesion_prostate_a_measurement,
            lesion_lymph_a: lesion_lymph_a,
            lesion_lymph_a_location: lesion_lymph_a_location,
            lesion_lymph_a_suv: lesion_lymph_a_suv,
            lesion_lymph_a_measurement: lesion_lymph_a_measurement,
            lesion_bone_a: lesion_bone_a,
            lesion_bone_a_location: lesion_bone_a_location,
            lesion_bone_a_suv: lesion_bone_a_suv,
            lesion_bone_a_measurement: lesion_bone_a_measurement,
            lesion_brain_a: lesion_brain_a,
            lesion_brain_a_location: lesion_brain_a_location,
            lesion_brain_a_suv: lesion_brain_a_suv,
            lesion_brain_a_measurement: lesion_brain_a_measurement,
            lesion_lungs_a: lesion_lungs_a,
            lesion_lungs_a_location: lesion_lungs_a_location,
            lesion_lungs_a_suv: lesion_lungs_a_suv,
            lesion_lungs_a_measurement: lesion_lungs_a_measurement,
            lesion_liver_a: lesion_liver_a,
            lesion_liver_a_location: lesion_liver_a_location,
            lesion_liver_a_suv: lesion_liver_a_suv,
            lesion_liver_a_measurement: lesion_liver_a_measurement,
            lesion_others_a: lesion_others_a,
            lesion_others_a_location: lesion_others_a_location,
            lesion_others_a_suv: lesion_others_a_suv,
            lesion_others_a_measurement: lesion_others_a_measurement,
            lesion_fdg_ct: lesion_fdg_ctr,
            lesion_prostate_b: lesion_prostate_b,
            lesion_prostate_b_location: lesion_prostate_b_location,
            lesion_prostate_b_suv: lesion_prostate_b_suv,
            lesion_prostate_b_measurement: lesion_prostate_b_measurement,
            lesion_lymph_b: lesion_lymph_b,
            lesion_lymph_b_location: lesion_lymph_b_location,
            lesion_lymph_b_suv: lesion_lymph_b_suv,
            lesion_lymph_b_measurement: lesion_lymph_b_measurement,
            lesion_bone_b: lesion_bone_b,
            lesion_bone_b_location: lesion_bone_b_location,
            lesion_bone_b_suv: lesion_bone_b_suv,
            lesion_bone_b_measurement: lesion_bone_b_measurement,
            lesion_brain_b: lesion_brain_b,
            lesion_brain_b_location: lesion_brain_b_location,
            lesion_brain_b_suv: lesion_brain_b_suv,
            lesion_brain_b_measurement: lesion_brain_b_measurement,
            lesion_lungs_b: lesion_lungs_b,
            lesion_lungs_b_location: lesion_lungs_b_location,
            lesion_lungs_b_suv: lesion_lungs_b_suv,
            lesion_lungs_b_measurement: lesion_lungs_b_measurement,
            lesion_liver_b: lesion_liver_b,
            lesion_liver_b_location: lesion_liver_b_location,
            lesion_liver_b_suv: lesion_liver_b_suv,
            lesion_liver_b_measurement: lesion_liver_b_measurement,
            lesion_others_b: lesion_others_b,
            lesion_others_b_location: lesion_others_b_location,
            lesion_others_b_suv: lesion_others_b_suv,
            lesion_others_b_measurement: lesion_others_b_measurement,
            assessment: assessment,
            plan: plan
        })
        .then(() => {
            res.json([{event :'success'}])
           
        })
        .catch((err) => {
            res.json([{event: 'error'}])
        })

})
module.exports = router